### PR TITLE
Easier to search MP list when grouped(?)

### PR DESCRIPTION
**Pull request by EdwardAndress**
MPs are now grouped by party in the drop down on the member tab.

If you two think this is the right thing to do, I will spend some time making the code nicer.  It's very ugly at the moment but improving it is beyond me today (I tried it and everything broke).

### CODE REVIEW

**Comment by RossKen** [comment]
@EdwardAndress just so you know, the dropdown for MPs also includes HoL names under 'Not found'

More generally, I think being able to use Party as a filter is a good idea, but not sure if this is the best way to do it. (Particularly in its current form as the names within the party sections have no apparent ordering so it is hard to tell when you scrolled to the end of one party and into another one.)

I think it may be better to have a separate dropdown for choosing which party's MP to show, then your split could be done as is if they choose multiple parties. Then have the default as all parties shown?

**Comment by EdwardAndress** [comment]
Ah yes, I remedied that business with the Lords whilst fiddling with improving the code and reverted it all by mistake, thanks.  I take your point with regards to the possibility of getting lost in the list but think this remains an improvement on the current version... I am, however, OK with leaving it out and implementing something better.

**Comment by RossKen** [comment]
Now that the MPs are ordered within the sections I think it is much better (or maybe that was something wrong with my local version the last time).

It is slightly unfortunate that the first MP you see has only asked one question, but not an awful lot can be done about that.

**Comment by EdwardAndress** [comment]
They were not initially ordered, I added that by amending the commit but you must have checked it out quicker than I could make the ammendment.

**Comment by EdwardAndress** [comment]
@RossKen I've amended the commit again to remove the peers. It's still totally OK to just park this though, if you think it's not right.

**Comment by EdwardAndress** [comment]
@samtazzyman I've made the change you requested and @RossKen you'll hopefully notice that the code is now cleaner.

**Comment by RossKen** [comment]
Found some strange behaviour
screen shot 2017-09-12 at 15 43 15

**Comment by EdwardAndress** [comment]
@RossKen - well spotted.  I don't know what's going on.  The list is generated in what appears to be the correct way, but I will fix it.

**Comment by EdwardAndress** [comment]
OK, this should be done now.

**Pull request merged**
