### PR TITLE
Sure up and test the intro

### PR DESCRIPTION
**Pull request by EdwardAndress**
- hide the next button at the step where the user should progress by clicking on 'see all questions by XYZ'

### CODE REVIEW

**Comment by RossKen** [comment]
This works, but you can still 'hit next' by using the arrow keys. Don't know if there is any way to stop this at this step. You can turn off the arrow key functionality completely, but would be nice to keep. Any thoughts?

**Comment by EdwardAndress** [comment]
@RossKen I agree that keyboard navigation is potentially useful.  We could disable it for that one step, but I don't think we can disable just the 'next' button.

**Comment by RossKen** [comment]
I think disabling for that step would be sufficient

**Comment by EdwardAndress** [comment]
@RossKen this is proving tricky but I shall resume tomorrow.

**Comment by EdwardAndress** [comment]
@RossKen - this is now functionally complete but I will try to refactor the nasty JS bits.  There's quite a bit of repetition now and it might become difficult to manage.  We could also do with one test that goes through the entire tour bumping into all the obstacles along the way.

**Comment by RossKen** [comment]
Functionality is really good @EdwardAndress. Yes, would be good to have slightly less repetition.

The work for disabling the button stroke will be useful later on for the issues when going from wordcloud to graph on the members page. Was playing about and it only seems to happen with the keyboard stroke, works fine when you click the next button.

Agreed on the test that goes through the intro, would be really good to make sure we have covered all bases

**Comment by EdwardAndress** [comment]
@RossKen test done... refactor of the JS to folllow.

**Comment by EdwardAndress** [comment]
@RossKen I think this could be improved further but not without significantly more fiddling around (and it's much better than it was).

**Comment by EdwardAndress** [comment]
Travis was failing on what looked like a race condition (page not loading quickly enough for the elements to be available for the test).  I've applied a quick tweak to test his hypothesis, extending the sleep time to 5 seconds (from 2).  If this works, I will find a way of using different sleep times on Travis vs you local machine.

**Pull request merged**
