### PR TITLE
Party refactor

### PR DESCRIPTION
**Pull request by EdwardAndress**
- It was necessary to refactor the party function as is was really inefficient.
- Now it just makes two API calls
- One to get the number of records to download and another to download all the records
- There is one known caveat at the moment : when there are two people with the same name, two parties are returned and I am not sure how to deal with this...  At the moment both are shown because I cannot work out how to determine the correct one.  See "Carmichael, Neil"

- Suggestions welcome!

### CODE REVIEW

**Comment by RossKen** [comment]
@EdwardAndress 

For member analysis page:
- you had mentioned putting the party above the graph with the member name, I think this would be clearer/less repetitive than having it on every row.
- Is there no party for HoL? A large portion of Peers are ex-MPs, so they would have some party affiliation?

**Comment by RossKen** [comment]
Also, have found something a bit strange with David Crausby whose party is only added for some of his qs
screen shot 2017-09-06 at 14 15 04

**Comment by EdwardAndress** [comment]
@RossKen - I'll address the first point in another piece of work (another PR)

As for parties for HoL members...

Looks like they don't hold that info: http://explore.data.parliament.uk/?endpoint=lordsmembers

That's an endpoint specifically for HoL but all the same data is combined with HoC members here: http://explore.data.parliament.uk/?endpoint=members

And if you retrieve JSON from that endpoint, for (at least this HoL member) it looks like this:
  {"_about" : "http://data.parliament.uk/members/1875", "additionalName" : {"_value" : "Huddleston"}
      , "familyName" : {"_value" : "Abney-Hastings"}
      , "fullName" : {"_value" : "Countess Loudoun"}
      , "gender" : {"_value" : "Female"}
      , "givenName" : {"_value" : "Barbara"}
      , "label" : {"_value" : "Biography information for Countess Loudoun"}
    }

**Comment by RossKen** [comment]
Ah ok, that makes sense.

**Comment by EdwardAndress** [comment]
Well spotted re: the inconsistency.  I suspect that what's going on is his name is inconsistently spelt / written and that causes some searches for party to fail.  The inconsistency is then cleared up when we process the data later on.  We should probably shift that bit to occur earlier on in the pipeline now.

**Comment by RossKen** [comment]
Sorry, me again.
In the member/topic pages, the child rows pull through the party instead of the question date
screen shot 2017-09-06 at 14 39 03

**Comment by EdwardAndress** [comment]
Great stuff.  Keep it coming.  I'm not at full capacity today so I appreciate the help :)

**Comment by samtazzyman** [comment]
On the David Crausby issue, he's down as both David and Sir David, we have to apply a special patch to make sure he's always consistently represented.

I expect you'll find the same thing with all the other nameCleaner special cases...

**Comment by EdwardAndress** [comment]
@samtazzyman - Thanks.  I'm now using nameCleaner to try and make sure both sets of names are consistent.

**Comment by EdwardAndress** [comment]
@RossKen I think I've fixed the anomalies you detected.  The one thing I am still not sure how to deal with is when two people have the same name.  Oh and when someone changes party.

**Pull request merged**
