### PR TITLE
Render HTML in other tabs now. Half of the error messages dealt with

### PR DESCRIPTION
**Pull request by andrewPoulton**
Bit of a hack.

### CODE REVIEW

**Comment by EdwardAndress** [comment]
@andrewPoulton - before you merge this, please have a look at this new branch: https://github.com/moj-analytical-services/pq-tool/tree/fix_error_messages_and_tables

I've branched it from this one and tried to improve the tables on MP and Topic Analysis tabs by using the same table layout as the Search tab (and the same JS functions).  See what you think.

**Comment by RossKen** [comment]
@EdwardAndress for the buttons in the childrows you have a button to take you to the page you are on - do you mean to have this?
(Eg. topic page gives a button to go to the page containing that topic)

**Comment by RossKen** [comment]
And when you try to choose the member button on the member page it breaks

**Comment by RossKen** [comment]
@EdwardAndress I think this branch should be merged as is and then deal with the tables separately, but happy to be convinced otherwise

**Pull request closed without merging**
